export const ROMANIA_COUNTIES = [
    { name: 'Alba', slug: 'alba', capital: 'Alba Iulia', population: 325941 },
    { name: 'Arad', slug: 'arad', capital: 'Arad', population: 410143 },
    { name: 'Argeș', slug: 'arges', capital: 'Pitești', population: 569932 },
    { name: 'Bacău', slug: 'bacau', capital: 'Bacău', population: 601387 },
    { name: 'Bihor', slug: 'bihor', capital: 'Oradea', population: 551297 },
    { name: 'Bistrița-Năsăud', slug: 'bistrita-nasaud', capital: 'Bistrița', population: 295988 },
    { name: 'Botoșani', slug: 'botosani', capital: 'Botoșani', population: 392821 },
    { name: 'Brașov', slug: 'brasov', capital: 'Brașov', population: 546615 },
    { name: 'Brăila', slug: 'braila', capital: 'Brăila', population: 281452 },
    { name: 'București', slug: 'bucuresti', capital: 'București', population: 1716961 },
    { name: 'Buzău', slug: 'buzau', capital: 'Buzău', population: 404979 },
    { name: 'Caraș-Severin', slug: 'caras-severin', capital: 'Reșița', population: 246588 },
    { name: 'Călărași', slug: 'calarasi', capital: 'Călărași', population: 283458 },
    { name: 'Cluj', slug: 'cluj', capital: 'Cluj-Napoca', population: 679141 },
    { name: 'Constanța', slug: 'constanta', capital: 'Constanța', population: 655997 },
    { name: 'Covasna', slug: 'covasna', capital: 'Sfântu Gheorghe', population: 200042 },
    { name: 'Dâmbovița', slug: 'dambovita', capital: 'Târgoviște', population: 479404 },
    { name: 'Dolj', slug: 'dolj', capital: 'Craiova', population: 599442 },
    { name: 'Galați', slug: 'galati', capital: 'Galați', population: 496892 },
    { name: 'Giurgiu', slug: 'giurgiu', capital: 'Giurgiu', population: 262066 },
    { name: 'Gorj', slug: 'gorj', capital: 'Târgu Jiu', population: 314685 },
    { name: 'Harghita', slug: 'harghita', capital: 'Miercurea Ciuc', population: 291950 },
    { name: 'Hunedoara', slug: 'hunedoara', capital: 'Deva', population: 361657 },
    { name: 'Ialomița', slug: 'ialomita', capital: 'Slobozia', population: 250816 },
    { name: 'Iași', slug: 'iasi', capital: 'Iași', population: 760774 },
    { name: 'Ilfov', slug: 'ilfov', capital: 'București', population: 542686 },
    { name: 'Maramureș', slug: 'maramures', capital: 'Baia Mare', population: 452478 },
    { name: 'Mehedinți', slug: 'mehedinti', capital: 'Drobeta-Turnu Severin', population: 265390 },
    { name: 'Mureș', slug: 'mures', capital: 'Târgu Mureș', population: 518193 },
    { name: 'Neamț', slug: 'neamt', capital: 'Piatra Neamț', population: 454203 },
    { name: 'Olt', slug: 'olt', capital: 'Slatina', population: 347019 },
    { name: 'Prahova', slug: 'prahova', capital: 'Ploiești', population: 735903 },
    { name: 'Satu Mare', slug: 'satu-mare', capital: 'Satu Mare', population: 330668 },
    { name: 'Sălaj', slug: 'salaj', capital: 'Zalău', population: 212224 },
    { name: 'Sibiu', slug: 'sibiu', capital: 'Sibiu', population: 388397 },
    { name: 'Suceava', slug: 'suceava', capital: 'Suceava', population: 641096 },
    { name: 'Teleorman', slug: 'teleorman', capital: 'Alexandria', population: 326651 },
    { name: 'Timiș', slug: 'timis', capital: 'Timișoara', population: 650533 },
    { name: 'Tulcea', slug: 'tulcea', capital: 'Tulcea', population: 193355 },
    { name: 'Vaslui', slug: 'vaslui', capital: 'Vaslui', population: 395499 },
    { name: 'Vâlcea', slug: 'valcea', capital: 'Râmnicu Vâlcea', population: 341861 },
    { name: 'Vrancea', slug: 'vrancea', capital: 'Focșani', population: 324380 }
].sort((a, b) => a.name.localeCompare(b.name));
